### ISSUE TITLE
Certified 10 ch sketch does not compile on 2.0.3 

### ISSUE THREAD

**Issue by michapr** [Z-Wave-Me/Z-Uno-Core#81]
Get compiling error:

if put the channel setup into one line (get more details):

C:\Users....\AppData\Local\Temp\build4213251842053482390.tmp_sketch_jul17b_ucxx.c:293: error 20: Undefined identifier 'ZUNO_ASSOC_BASIC_SET_NUMBER'
C:\Users....\AppData\Local\Temp\build4213251842053482390.tmp_sketch_jul17b_ucxx.c:293: error 20: Undefined identifier 'ZUNO_ASSOC_BASIC_SET_NUMBER'
Error. SDCC returned: 1

Order:{'flush00': 3, 'read00': 5, 'peek00': 4, 'write0105': 0, 'write02p0508': 1, 'available00': 2} Override:[] NewMethods:['__cxx__Stream__method__available00', '__cxx__Stream__method__read00', '__cxx__Stream__method__peek00', '__cxx__Stream__method__flush00']
Order:{'flush00': 3, 'read00': 5, 'peek00': 4, 'write0105': 0, 'write02p0508': 1, 'available00': 2} Override:['__cxx__HardwareSerial__method__available00', '__cxx__HardwareSerial__method__peek00', '__cxx__HardwareSerial__method__read00', '__cxx__HardwareSerial__method__flush00', '__cxx__HardwareSerial__method__write0105'] NewMethods:[]

Michael

**Comment by michapr** [comment]
is working with 2.04 now.

Michael
